/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
extend: {
      colors: {
        primary: '#FFB6C1',
        secondary: '#FFC0CB',
        accent: '#FF69B4',
        surface: '#FFF0F5',
        background: '#FFEBEF',
        rose: {
          50: '#fdf2f8',
          100: '#fce7f3',
          200: '#fbcfe8',
          300: '#f9a8d4',
          400: '#f472b6',
          500: '#ec4899',
          600: '#db2777',
          700: '#be185d',
          800: '#9d174d',
          900: '#831843',
        },
        lavender: {
          50: '#faf5ff',
          100: '#f3e8ff',
          200: '#e9d5ff',
          300: '#d8b4fe',
          400: '#c084fc',
          500: '#a855f7',
          600: '#9333ea',
          700: '#7c3aed',
          800: '#6b21a8',
          900: '#581c87',
        },
        gold: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
        },
        success: '#98D982',
        warning: '#FFD700',
        error: '#FF6B6B',
        info: '#87CEEB',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        body: ['Inter', 'sans-serif'],
        cursive: ['Dancing Script', 'cursive'],
        romantic: ['Dancing Script', 'cursive'],
      },
animation: {
        'float-heart': 'float-heart 6s ease-in-out infinite',
        'pulse-heart': 'pulse-heart 2s ease-in-out infinite',
        'typewriter': 'typewriter 3s steps(40, end)',
        'fade-in-up': 'fade-in-up 0.8s ease-out',
        'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
        'sparkle': 'sparkle 2s ease-in-out infinite',
        'romantic-glow': 'romantic-glow 3s ease-in-out infinite',
        'gentle-sway': 'gentle-sway 4s ease-in-out infinite',
        'flower-bloom': 'flower-bloom 3s ease-in-out infinite',
        'gift-bounce': 'gift-bounce 2s ease-in-out infinite',
        'float-decoration': 'float-decoration 8s ease-in-out infinite',
      },
keyframes: {
        'float-heart': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '50%': { transform: 'translateY(-20px) rotate(10deg)' },
        },
        'pulse-heart': {
          '0%, 100%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(1.1)' },
        },
        'typewriter': {
          '0%': { width: '0' },
          '100%': { width: '100%' },
        },
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'bounce-gentle': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'sparkle': {
          '0%, 100%': { opacity: '0', transform: 'scale(0) rotate(0deg)' },
          '50%': { opacity: '1', transform: 'scale(1) rotate(180deg)' },
        },
        'romantic-glow': {
          '0%, 100%': { boxShadow: '0 0 20px rgba(255, 182, 193, 0.4)' },
          '50%': { boxShadow: '0 0 40px rgba(255, 182, 193, 0.8)' },
        },
        'gentle-sway': {
          '0%, 100%': { transform: 'translateX(0px) rotate(0deg)' },
          '33%': { transform: 'translateX(10px) rotate(1deg)' },
          '66%': { transform: 'translateX(-5px) rotate(-0.5deg)' },
        },
        'flower-bloom': {
          '0%': { transform: 'scale(0) rotate(0deg)', opacity: '0' },
          '50%': { transform: 'scale(1.1) rotate(180deg)', opacity: '1' },
          '100%': { transform: 'scale(1) rotate(360deg)', opacity: '0.8' },
        },
        'gift-bounce': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'float-decoration': {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '25%': { transform: 'translateY(-20px) rotate(5deg)' },
          '50%': { transform: 'translateY(-10px) rotate(-5deg)' },
          '75%': { transform: 'translateY(-25px) rotate(3deg)' },
        },
      },
    },
  },
  plugins: [],
}